### ISSUE TITLE
Using external PostgreSQL database doesn't work

### ISSUE THREAD

**Issue by UncleSamSwiss** [WeblateOrg/helm#142]
### Describe the issue

When setting `postgresql.enabled` to `false`, the entire `POSTGRES_* ` environment variable block is missing.

In the values file it says:
```yml
  # postgresql.postgresqlHost -- External postgres database endpoint, to be
  # used if `postgresql.enabled == false`
```

But in the deployment the entire block is omitted if `postgresql.enabled` is `false`:
https://github.com/WeblateOrg/helm/blob/c009d08912a252305ec0d3bb48ff6c9a468eb91c/charts/weblate/templates/deployment.yaml#L44-L61

The value of `postgresqlHost` would have been used in the following line:
https://github.com/WeblateOrg/helm/blob/c009d08912a252305ec0d3bb48ff6c9a468eb91c/charts/weblate/templates/deployment.yaml#L48

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Create a helm release with values similar to this one:
```yml
postgresql:
  enabled: false
  postgresqlUsername: weblate
  postgresqlDatabase: weblate
  postgresqlHost: my-external-psql-server.com
```
2. The release will fail with an error:
```
KeyError: 'POSTGRES_DATABASE'
```

### Expected behavior

All `POSTGRES_* ` environment variables are still set even if `postgresql.enabled` is `false`.

### Exception traceback

```pytb
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/weblate/runner.py", line 36, in main
    from weblate.utils.errors import report_error
  File "/usr/local/lib/python3.10/site-packages/weblate/utils/errors.py", line 32, in <module>
    import weblate.utils.version
  File "/usr/local/lib/python3.10/site-packages/weblate/utils/version.py", line 23, in <module>
    from weblate.vcs.base import RepositoryException
  File "/usr/local/lib/python3.10/site-packages/weblate/vcs/base.py", line 38, in <module>
    from weblate.utils.lock import WeblateLock
  File "/usr/local/lib/python3.10/site-packages/weblate/utils/lock.py", line 23, in <module>
    from django_redis.cache import RedisCache
  File "/usr/local/lib/python3.10/site-packages/django_redis/cache.py", line 12, in <module>
    DJANGO_REDIS_SCAN_ITERSIZE = getattr(settings, "DJANGO_REDIS_SCAN_ITERSIZE", 10)
  File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 84, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 71, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 179, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/site-packages/weblate/settings_docker.py", line 67, in <module>
    "NAME": os.environ["POSTGRES_DATABASE"],
  File "/usr/local/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
```

**Comment by nijel** [comment]
The logic of these is confusing, you should use `externalSecretName`. Patches to make this less confusing are welcome.

See related issues/pull requests:

* https://github.com/WeblateOrg/helm/pull/116
* https://github.com/WeblateOrg/helm/issues/121
* https://github.com/WeblateOrg/helm/pull/136

**Comment by anton-yurchenko** [comment]
I was able to deploy it with the following config:

```yaml
extraConfig:
  POSTGRES_DATABASE: XXX
  POSTGRES_HOST: XXX
  POSTGRES_PORT: "5432"
  POSTGRES_USER: XXX
  POSTGRES_PASSWORD: XXX

postgresql:
  enabled: false
```

**Comment by nijel** [comment]
This might give a guidance for rewriting this part:
https://github.com/sentry-kubernetes/charts#upgrading-from-310-version-of-this-chart-to-400
