### ISSUE TITLE
Chart not installable due to removed dependencies

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/helm#163]
### Describe the issue

As a result of https://github.com/bitnami/charts/issues/10539 the dependencies of the chart are gone. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

I've tried to update the dependencies, but then Weblate fails to authenticate with redis, see https://github.com/WeblateOrg/helm/runs/6769378543?check_suite_focus=true#step:9:269

```pytb
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/weblate/runner.py", line 34, in main
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/usr/local/lib/python3.10/site-packages/weblate/vcs/apps.py", line 86, in ready
    with lockfile:
  File "/usr/local/lib/python3.10/site-packages/weblate/utils/lock.py", line 81, in __enter__
    if not self._lock.acquire(timeout=self._timeout):
  File "/usr/local/lib/python3.10/site-packages/redis_lock/__init__.py", line 226, in acquire
    if self._held:
  File "/usr/local/lib/python3.10/site-packages/redis_lock/__init__.py", line 197, in _held
    return self.id == self.get_owner_id()
  File "/usr/local/lib/python3.10/site-packages/redis_lock/__init__.py", line 210, in get_owner_id
    owner_id = self._client.get(self._name)
  File "/usr/local/lib/python3.10/site-packages/redis/commands/core.py", line 1600, in get
    return self.execute_command("GET", name)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1215, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 1386, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 626, in connect
    self.on_connect()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 716, in on_connect
    auth_response = self.read_response()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 836, in read_response
    raise response
redis.exceptions.ResponseError: WRONGPASS invalid username*** or user is disabled.
```

### Expected behavior

* The chart dependencies should be kept up to date (is there something like dependabot for this)?
* Setup regular testing of the chart to get noticed of such breakages earlier than somebody submits a PR.

**Comment by clawoflight** [comment]
@nijel When I pull/upgrade weblate, I still get the version of the chart without commit https://github.com/WeblateOrg/helm/commit/b9cc2aa39185a1323971e83fa48fb99e05aa1569, with postgres 11 and redis 16.

Do we need a version bump on the chart or something?

**Comment by nijel** [comment]
The chart with revert failed to publish because of missing deps (see https://github.com/WeblateOrg/helm/runs/6771194355?check_suite_focus=true). I will look into solution to publish something working...

The auto-updating should be handled in https://github.com/WeblateOrg/helm/issues/165.

**Comment by clawoflight** [comment]
Oh, I see. Thanks a lot and sorry for the bother! :)

**Comment by pc-jedi** [comment]
@nijel Sorry for bothering you, but I cannot see the version 0.4.11 been available on helm.weblate.org.
I guess the tag here on GH is missing for that?

**Comment by nijel** [comment]
There were indeed some additional issues in publishing it, it should be now there - https://github.com/WeblateOrg/helm/actions/runs/2527470126
