### ISSUE TITLE
Redis 6 compatibility

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/helm#168]
### Describe the issue

When updating the chart to Redis 6 it fails to start:

```pytb
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/weblate/runner.py", line 34, in main
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/usr/local/lib/python3.10/site-packages/weblate/vcs/apps.py", line 86, in ready
    with lockfile:
  File "/usr/local/lib/python3.10/site-packages/weblate/utils/lock.py", line 81, in __enter__
    if not self._lock.acquire(timeout=self._timeout):
  File "/usr/local/lib/python3.10/site-packages/redis_lock/__init__.py", line 226, in acquire
    if self._held:
  File "/usr/local/lib/python3.10/site-packages/redis_lock/__init__.py", line 197, in _held
    return self.id == self.get_owner_id()
  File "/usr/local/lib/python3.10/site-packages/redis_lock/__init__.py", line 210, in get_owner_id
    owner_id = self._client.get(self._name)
  File "/usr/local/lib/python3.10/site-packages/redis/commands/core.py", line 1600, in get
    return self.execute_command("GET", name)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1215, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 1386, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 626, in connect
    self.on_connect()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 716, in on_connect
    auth_response = self.read_response()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 836, in read_response
    raise response
redis.exceptions.ResponseError: WRONGPASS invalid username*** or user is disabled.
```

It is most likely caused by wrongly generated configuration, either in the Docker image itself or in the chart. We do test Docker images with Redis 6, but AFAIK it is not using password there, while the chart is, so that might make the difference.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Updated the redis chart to latest one
2. See the error https://github.com/WeblateOrg/helm/runs/6769378543?check_suite_focus=true#step:9:269

**Comment by gllb** [comment]
#195

**Comment by nijel** [comment]
Fixed by https://github.com/WeblateOrg/helm/pull/195
