### ISSUE TITLE
Fails to start if data volume is mounted via CIFS or NFS

### ISSUE THREAD

**Issue by gilfthde** [WeblateOrg/helm#251]
### Describe the issue

I'm trying to deploy Weblate on a Azure Kubernetes Cluster and want to mount the `/app/data` directory from a volume based on Azure Files. This results in the volume being mounted using either the `CIFS` or `NFS` protocol. However when I try to do this Weblate fails to start because `celery beat` is not able to (re-)create its database file.

It works if I provide the volume backed by a disk or the default `EmptyDir`. 

This [issue comment](https://github.com/cookiecutter/cookiecutter-django/issues/1793#issuecomment-440406112) mentions that the underlying `gdbm` lib shows problems like this when using network filesystems. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Trying to generalize the instructions so that it may show the issue on a generic cluster:

1. Create a Persistent Volume Claim based on a volume backed by a `CIFS` or `NFS` file system.
2. Deploy the chart with the value `persistence.existingClaim` set to this PVC

### Expected behavior

The pod should start.

### Exception traceback

```pytb
Starting...
Postgres 130008 is up
Starting database migration...
Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, configuration, contenttypes, fonts, gitexport, glossary, lang, memory, metrics, screenshots, sessions, social_django, trans, utils, vcs, weblate_auth, wladmin
Running migrations:
  No migrations to apply.
Updating user admin
Refreshing stats...
Removing corrupted schedule file: error(2, 'No such file or directory')
[2023-01-19 09:45:13,511: WARNING/164] Handled exception: FileNotFoundError: [Errno 2] No such file or directory: '/app/data/celery/beat-schedule'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/beat.py", line 533, in setup_schedule
    self._store = self._open_schedule()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/beat.py", line 523, in _open_schedule
    return self.persistence.open(self.schedule_filename, writeback=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
_gdbm.error: [Errno 11] Resource temporarily unavailable: '/app/data/celery/beat-schedule'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/weblate/utils/management/commands/cleanup_celery.py", line 45, in handle
    self.setup_schedule()
  File "/usr/local/lib/python3.11/site-packages/weblate/utils/management/commands/cleanup_celery.py", line 41, in setup_schedule
    scheduler.setup_schedule()
  File "/usr/local/lib/python3.11/site-packages/celery/beat.py", line 541, in setup_schedule
    self._store = self._destroy_open_corrupted_schedule(exc)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/beat.py", line 529, in _destroy_open_corrupted_schedule
    return self._open_schedule()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/beat.py", line 523, in _open_schedule
    return self.persistence.open(self.schedule_filename, writeback=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dbm/__init__.py", line 95, in open
    return mod.open(file, flag, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
_gdbm.error: [Errno 2] No such file or directory: '/app/data/celery/beat-schedule'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 34, in main
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/weblate/utils/management/base.py", line 42, in execute
    return super().execute(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weblate/utils/management/commands/cleanup_celery.py", line 48, in handle
    self.try_remove(settings.CELERY_BEAT_SCHEDULE_FILENAME)
  File "/usr/local/lib/python3.11/site-packages/weblate/utils/management/commands/cleanup_celery.py", line 35, in try_remove
    os.remove(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/app/data/celery/beat-schedule'
```

**Comment by nijel** [comment]
Is the storage healthy? That code just tries to create a file there, and it fails with “Resource temporarily unavailable”. The “No such file or directory” error is just bad error handling after that failure, I've just fixed that. 

The referenced Celery issue is getting another error, so I'm uncertain whether it's related. However they mention creating the directory manually, have you tried that?

**Comment by gilfthde** [comment]
The storage is healthy at this point in time. The startup of Weblate did already populate other directories including `/app/data/celery/` but the file `beat-schedule` is missing in it.

**Comment by nijel** [comment]
Unfortunately, the dbm library doesn't tell where it failed. One thing it does as well is locking, but I think that should work on both file systems you are using.

Anyway, this will most likely disappear in Weblate 4.16, see https://github.com/WeblateOrg/weblate/pull/8635
